//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayitId { get; set; }
        public string kayitDersiAlanOgrId { get; set; }
        public string kayitDerslerId { get; set; }
    
        public virtual DersiAlanOgr DersiAlanOgr { get; set; }
        public virtual Dersler Dersler { get; set; }
    }
}
